# Generated by Django 2.2.16 on 2020-09-24 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import edx_analytics_transformers.utils.fields
import jsonfield.encoder
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_name', models.CharField(help_text='Name of the tracking backend on which this router should be applied.<br/>Please note that this field is <b>case sensitive.</b>', max_length=50, verbose_name='Backend name')),
                ('enterprise_uuid', models.UUIDField(blank=True, null=True, verbose_name='Enterprise UUID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('configurations', edx_analytics_transformers.utils.fields.EncryptedJSONField(dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={})),
            ],
            options={
                'ordering': ('backend_name', 'is_enabled'),
                'verbose_name': 'Router Configurations',
                'unique_together': {('backend_name', 'enterprise_uuid')},
                'verbose_name_plural': 'Router Configurations',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRouterConfiguration',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('backend_name', models.CharField(help_text='Name of the tracking backend on which this router should be applied.<br/>Please note that this field is <b>case sensitive.</b>', max_length=50, verbose_name='Backend name')),
                ('enterprise_uuid', models.UUIDField(blank=True, null=True, verbose_name='Enterprise UUID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('configurations', edx_analytics_transformers.utils.fields.EncryptedJSONField(dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={})),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Router Configurations',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
